name: Builds Dist Directory

on:
  push:
    branches:
      - master

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci || npm install

      - name: Run unit tests
        run: npm run test --if-present

  build-and-upload:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci || npm install

      - name: Build the package
        run: npm run build --if-present

      - name: Upload dist directory
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
          retention-days: 1

  download-dist:
    name: Download dist directory
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download dist directory
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

